accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from .views import UserCreateView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('login', LoginView.as_view(), name='login'),
    path('login', LoginView.as_view(), name='login'),
]

djcrm/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from leads.views import LandingPageView

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('leads/', include('leads.urls', namespace="leads")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from leads.views import LeadDeleteView, LeadDetailView, LeadListView, LeadCreateView, LeadUpdateView


app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_list'),
    path('create/', LeadCreateView.as_view(), name='lead_create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead_delete')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

        

leads/models.py
from django.db import models
from accounts.models import User, UserProfile
from django.db.models.signals import pre_save, post_save
# Create your models here.

class Lead(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField(default=0)
    # the foreignkey is placed in the leads models
    # because every lead has its own agent and not the other way around
    agent = models.ForeignKey('Agent', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, related_name="leads", on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.user.email


def user_profile_create_signal(sender, instance, created, *args, **kwargs):
    print('Creating a user profile using the signals')
    if created:
        UserProfile.objects.create(user=instance)



post_save.connect(user_profile_create_signal, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()

class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

leads/forms.py
from django import forms

from leads.models import Lead


class LeadCreateForm(forms.Form):
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=100)
    age = forms.IntegerField(min_value=0)



class LeadCreateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['first_name', 'last_name', 'age', 'agent']

accounts/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView
from .models import User
from .forms import UserCreateForm


class UserCreateView(CreateView):
    template_name = 'registration/signup.html'
    form_class = UserCreateForm

    def get_success_url(self) -> str:
        return reverse('accounts:login')


    def form_valid(self, form):
        return super(UserCreateView, self).form_valid(form)

leads/views.py
from email import message
from operator import sub
from django.core.mail import send_mail
from django.shortcuts import redirect, render, reverse
from .models import Lead, Agent
from .forms import LeadCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.views import LoginView
# Create your views here.

class LandingPageView(generic.TemplateView):
    template_name = 'landing_page.html'

    

class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/leads_list.html'
    queryset = Lead.objects.all()
    context_object_name = 'leads'



class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'leads/lead_detail.html'
    model = Lead
    queryset = Lead.objects.all()
    context_object_name = 'lead'
 
 
class LeadCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadCreateForm

    def get_success_url(self):
        return reverse('leads:lead_list')

    def form_valid(self, form):
        subject = 'Lead Created'
        message = 'You have successfuly created a lead'
        send_mail(subject=subject, message=message, from_email='crm@mail.com', recipient_list=['miclem@mail.com;'])
        return super(LeadCreateView, self).form_valid(form)
    

class LeadUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadCreateForm
    
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead_list')


class LeadDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/lead_delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead_list')

    

leads/templates/leads/lead_create.html
{% extends "base.html" %}


{% block title %}
    Create lead
{% endblock title %}


{% block content %}
  <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}  
      <button type="submit">Submit</button>
  </form>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        Would you like to <button type="submit">delete</button> this object 
    </form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}



{% block content %}
    <a href="">Go back to leads</a>
  <h2>This is the detail of {{lead.first_name}} {{last_name}}</h2>
  <a href="{% url 'leads:lead_delete' lead.pk %}">Delete lead</a>



  <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">Animated Night Hill Illustrations</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Color</span>
            <span class="ml-auto text-gray-900">Blue</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Size</span>
            <span class="ml-auto text-gray-900">Medium</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Quantity</span>
            <span class="ml-auto text-gray-900">4</span>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
  
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">
        {{form}}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

leads/templates/leads/leads_list.html
{% extends 'base.html' %}


{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
          <div class="flex flex-wrap -m-4">
            {% for lead in leads %}
            <div class="p-4 lg:w-1/2 md:w-full">
              <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <div class="flex-grow">
                  <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead_lastname}}</h2>
                  <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                  <a href="{% url 'leads:lead_detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
           {% endfor %}
          </div>
        </div>
      </section>

        <h1>{{ lead.first_name}} is lead number {{forloop.counter}}</h1>

{% endblock content %}

templates/base.html
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css %}
    
    <title>{% block title %}
    {% endblock title %}</title>
</head>

<body>
    {% include "./utils/navigation.html" %}
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        {% block content %}
        
        {% endblock content %}
    
        {% block scripts %}
        
        {% endblock scripts %}
    </div>
</body>
</html>

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://flowbite.com/docs/images/people/profile-picture-3.jpg">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Microdosing synth tattooed vexillologist</h1>
        <p class="mb-8 leading-relaxed">Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over meditation PBR&B pickled ennui celiac mlkshk freegan photo booth af fingerstache pitchfork.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/utils/navigation.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Tailblocks</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_authenticated %}
        <a href="{% url 'leads:lead_create' %}" class="mr-5 hover:text-gray-900">Create lead</a>
        <a href="{% url 'accounts:logout' %}" class="mr-5 hover:text-gray-900">Logout</a>
      {% else %}
        <a href="{% url 'accounts:login' %}" class="mr-5 hover:text-gray-900">Login</a>

      {% endif %}
    </nav>
    <a href="{% url 'leads:lead_list' %}"><button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Leads
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button></a>
  </div>
</header>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>